# Global config: ~/Library/Preferences/DOSBox/dosbox-staging.conf

[sdl]
#fullscreen=false
#fullresolution=desktop

[cpu]
#cycles=fixed 20000

[autoexec]
mount c ~/dosgames
c:
cd ancient
aeprog.exe
exit

