# Global config: ~/Library/Preferences/DOSBox/dosbox-staging.conf

[sdl]
#fullscreen=false

[cpu]
cycles=15000
core=dynamic

[autoexec]
mount c ~/dosgames/rescue/windows
imgmount e ~/dosgames/rescue/ssrwincd.iso -t cdrom
mount d ~/dosgames
c:
cd windows
win

